# Generated by Django 5.0.3 on 2026-03-04 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('codigo_iso', models.CharField(help_text='Código ISO 3166-1 alpha-2 ou alpha-3.', max_length=3, unique=True, verbose_name='Código ISO')),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to='bandeiras/', verbose_name='Bandeira')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catalogo', models.CharField(help_text='Referência no catálogo Stanley Gibbons, Yvert, etc.', max_length=50, verbose_name='Número de Catálogo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano de Emissão')),
                ('denominacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Denominação')),
                ('moeda', models.CharField(max_length=10, verbose_name='Moeda')),
                ('descricao_tematica', models.TextField(help_text='Descreve o tema ou motivo representado no selo.', verbose_name='Descrição Temática')),
                ('descricao_tecnica', models.TextField(blank=True, help_text='Dentado, formato, método de impressão, tiragem, etc.', verbose_name='Descrição Técnica')),
                ('dentado', models.CharField(blank=True, help_text='Ex.: 14 x 13½', max_length=50, verbose_name='Dentado')),
                ('tiragem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiragem')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='selos/', verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selos', to='catalog.pais', verbose_name='País')),
                ('temas', models.ManyToManyField(blank=True, related_name='selos', to='catalog.tema', verbose_name='Temas')),
            ],
            options={
                'verbose_name': 'Selo',
                'verbose_name_plural': 'Selos',
                'ordering': ['pais', 'ano', 'numero_catalogo'],
                'unique_together': {('pais', 'numero_catalogo')},
            },
        ),
    ]
