# Generated by Django 5.0.3 on 2026-03-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selo',
            name='numero_mundifil',
            field=models.CharField(blank=True, help_text='Referência no catálogo Mundifil.', max_length=50, verbose_name='Nº Mundifil'),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código / Designação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('selo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.selo', verbose_name='Selo')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['codigo'],
            },
        ),
    ]
