# Generated by Django 5.0.3 on 2026-03-04 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_selo_numero_mundifil_variante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da emissão / issue (ex.: «Ceres», «Route of the Portuguese Cathedrals»).', max_length=200, verbose_name='Nome da Série')),
                ('data_emissao', models.DateField(blank=True, help_text='Data em que a série foi emitida.', null=True, verbose_name='Data de Emissão')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='catalog.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['pais', '-data_emissao', 'nome'],
                'unique_together': {('pais', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='selo',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Série / emissão a que o selo pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selos', to='catalog.serie', verbose_name='Série'),
        ),
    ]
