# Generated by Django 5.0.3 on 2026-03-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_serie_model_e_fk_selo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(help_text='Código ISO 3166-1 alpha-2/alpha-3, ou código customizado (ex.: PT-AZ).', max_length=10, unique=True, verbose_name='Código ISO'),
        ),
    ]
