# Generated by Django 5.0.3 on 2026-03-05 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_codigo_iso_max_length_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_id', models.IntegerField(verbose_name='StampData Issuer ID')),
                ('estado', models.CharField(choices=[('a_correr', 'A correr'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='a_correr', max_length=20, verbose_name='Estado')),
                ('fase_atual', models.CharField(blank=True, max_length=300, verbose_name='Fase atual')),
                ('total_ids', models.IntegerField(default=0, verbose_name='Total de IDs encontrados')),
                ('ids_processados', models.IntegerField(default=0, verbose_name='IDs processados (scrape)')),
                ('selos_criados', models.IntegerField(default=0, verbose_name='Selos criados')),
                ('selos_atualizados', models.IntegerField(default=0, verbose_name='Selos atualizados')),
                ('erros_importacao', models.IntegerField(default=0, verbose_name='Erros de importação')),
                ('imagens_total', models.IntegerField(default=0, verbose_name='Imagens a descarregar')),
                ('imagens_processadas', models.IntegerField(default=0, verbose_name='Imagens processadas')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_catalogo', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to='catalog.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Importação de Catálogo',
                'verbose_name_plural': 'Importações de Catálogo',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
