# Generated by Django 5.0.3 on 2026-03-06 09:17

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_importacaocatalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.selo_imagem_upload_path, verbose_name='Imagem'),
        ),
    ]
