# Generated by Django 5.0.3 on 2026-03-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_possuida', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade Possuída')),
                ('quantidade_repetidos', models.PositiveSmallIntegerField(default=0, verbose_name='Repetidos (disponíveis para troca)')),
                ('condicao', models.CharField(choices=[('mint', 'Mint (perfeito)'), ('used', 'Usado'), ('cto', 'CTO (cancelado por encomenda)'), ('no_gum', 'Sem goma'), ('damaged', 'Com defeito')], default='mint', max_length=20, verbose_name='Condição')),
                ('notas', models.TextField(blank=True, verbose_name='Notas pessoais')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_colecao', to='catalog.selo', verbose_name='Selo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_colecao', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Item da Coleção',
                'verbose_name_plural': 'Itens da Coleção',
                'ordering': ['stamp__pais__nome', 'stamp__ano'],
                'unique_together': {('utilizador', 'stamp')},
            },
        ),
    ]
