# Generated by Django 5.0.3 on 2026-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_selo_numero_mundifil_variante'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolecao',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex.: Álbum A, Caixa 3, Envelope azul…', max_length=100, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='itemcolecao',
            name='variantes_possuidas',
            field=models.ManyToManyField(blank=True, to='catalog.variante', verbose_name='Variantes possuídas'),
        ),
    ]
