# Generated by Django 5.0.3 on 2026-03-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre o colecionador.', verbose_name='Biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de Perfil')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('paises_interesse', models.ManyToManyField(blank=True, related_name='utilizadores_interessados', to='catalog.pais', verbose_name='Países de Interesse')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil do Utilizador',
                'verbose_name_plural': 'Perfis dos Utilizadores',
            },
        ),
    ]
