# Generated by Django 5.0.3 on 2026-03-04 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aceite', 'Aceite'), ('concluida', 'Concluída'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Estado')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciador')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recetor')),
                ('selos_oferecidos', models.ManyToManyField(related_name='trocas_como_oferta', to='catalog.selo', verbose_name='Selos Oferecidos pelo Iniciador')),
                ('selos_pedidos', models.ManyToManyField(related_name='trocas_como_pedido', to='catalog.selo', verbose_name='Selos Pedidos ao Recetor')),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OfertaTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disponivel', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade Disponível')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('selo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='catalog.selo', verbose_name='Selo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_troca', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Oferta de Troca',
                'verbose_name_plural': 'Ofertas de Troca',
                'ordering': ['-data_criacao'],
                'unique_together': {('utilizador', 'selo')},
            },
        ),
        migrations.CreateModel(
            name='PedidoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pretendida', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade Pretendida')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('selo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='catalog.selo', verbose_name='Selo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_troca', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Pedido de Troca',
                'verbose_name_plural': 'Pedidos de Troca',
                'ordering': ['-data_criacao'],
                'unique_together': {('utilizador', 'selo')},
            },
        ),
    ]
